force-app/main/default/objects/Guild__c/Guild__c.object-meta.xml
<CustomObject>
    <label>Guild</label>
    <nameField>
        <label>Guild Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guilds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rank</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Rank.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>S</fullName>
    </customValue>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>B</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>D</fullName>
        <default>true</default>
        <label>D</label>
    </customValue>
    <masterLabel>Rank</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Service.cls
public with sharing class Service {
    public static final String COMPLETED_STATUS = 'Completed';
    public static final String IN_PROGRESS_STATUS = 'In Progress';

    public static final Map<String, Integer> RANK_MAP = new Map<String, Integer>{
        'S' => 1,
        'A' => 2,
        'B' => 3,
        'C' => 4,
        'D' => 5
    };

    public static Hero__c currentHero {
        get {
            if (currentHero == null) {
                Contact userContact = [SELECT Id FROM Contact WHERE Id IN (SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId())];
                System.debug(userContact);
                currentHero = [SELECT Id, Guild__c, Rank__c FROM Hero__c WHERE Contact__c = :userContact.Id];
            }

            return currentHero;
        }
        private set;
    }

}