force-app/main/default/objects/Guild__c/Guild__c.object-meta.xml
<CustomObject>
    <label>Guild</label>
    <nameField>
        <label>Guild Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guilds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hero__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rank</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Superhero_Mission__c/Superhero_Mission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Superhero_Mission__c/fields/Complexity_Rank__c.field-meta.xml
<CustomField>
    <fullName>Complexity_Rank__c</fullName>
    <label>Complexity Rank</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rank</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Rank.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>S</fullName>
    </customValue>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>B</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>D</fullName>
        <default>true</default>
        <label>D</label>
    </customValue>
    <masterLabel>Rank</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AllMissionsControllerTest.cls
@IsTest
private class AllMissionsControllerTest {

    @TestSetup
    static void testSetup(){
        Account account = new Account(Name = 'Test Acc');
        insert account;

        Contact contact = new Contact(LastName = 'Test', AccountId = account.Id);
        insert contact;

        Profile customerProfile = [SELECT Id FROM Profile WHERE Name = 'Customer Community user' LIMIT 1];
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];

        User adminUser = new User(
            Username = 'test_' + Math.random() + '@test.com',
            LastName = 'Test-Admin',
            Alias = 'adm',
            Email = 'test' + Math.random() + '@test.com',
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            ProfileId = adminProfile.Id
        );
        insert adminUser;

        User customerUser = new User(
            Username = 'test_' + Math.random() + '@test.com',
            LastName = 'Test-Last',
            Alias = 'test',
            Email = 'test' + Math.random() + '@test.com',
            TimeZoneSidKey = 'America/New_York',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            ProfileId = customerProfile.Id,
            ContactId = contact.Id
        );
        insert customerUser;

        System.runAs(adminUser){
            PermissionSet permissionSet = [SELECT Id FROM PermissionSet WHERE Name = 'Hero_User'];
            PermissionSetAssignment psa = new PermissionSetAssignment();
            psa.AssigneeId = customerUser.Id;
            psa.PermissionSetId = permissionSet.Id;
            insert psa;
        }

        Guild__c guild = new Guild__c(Name = 'Test guild');
        insert guild;

        Hero__c hero = new Hero__c(
            Name = 'TestHero',
            Contact__c = contact.Id,
            Guild__c = guild.Id,
            Rank__c = 'A'
        );
        insert hero;

        Superhero_Mission__c mission = new Superhero_Mission__c(
            Subject__c = 'TestMission',
            Guild__c = guild.Id,
            Complexity_Rank__c = 'A',
            Details__c = 'test'
        );
        insert mission;
    }

    @IsTest
    static void getMissionsTest() {
        User user = [SELECT Id, ContactId FROM User WHERE LastName = 'Test-Last'];
        List<Superhero_Mission__c> missions = new List<Superhero_Mission__c>();
        System.runAs(user){
            missions.addAll(AllMissionsController.getMissions());
        }
        System.assertEquals(1, missions.size());
    }
}